recipe: default.v1

assistant_id: 20230420-022933-allegro-shark

language: pt-br
pipeline:
- name: WhitespaceTokenizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 16
- name: CountVectorsFeaturizer
  analyzer: word
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 350
  model_confidence: softmax
  constrain_similarities: true
  use_masked_language_model: true
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 350
  model_confidence: softmax
  constrain_similarities: true
- name: FallbackClassifier
  threshold: 0.5
  ambiguity_threshold: 0.1
  
policies:
- name: RulePolicy
  model_confidence: softmax
  constrain_similarities: true
- name: TEDPolicy
  epochs: 350
  model_confidence: softmax
  constrain_similarities: true
